### ISSUE TITLE
There should be only one "Create" button

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Content#11]
### Steps to reproduce

1. Start Content branch `compatibility-fix`
2. Start SignIn branch `Replace-ImageURL-with-Illustration-#58`
3. Go to `http://localhost:8080/signin/generateadminuser` to generate the admin user
4. Go to `http://localhost:8080/content/cms`
5. Sign in as admin user
6. Look at the "Create" buttons

### Expected result

For any typical UI action an app should have a single button.

### Actual result

There are two "Create" buttons, marked in red rectangle on the screenshot

### Screenshot

![2017-01-20 22_18_17-content](https://cloud.githubusercontent.com/assets/566463/22165930/b1e5c900-df5e-11e6-8c01-c83624c4db2d.png)

**Comment by diliger** [comment]
I prefer the top one, so bottom will be removed.

**Comment by diliger** [comment]
Done.
