### ISSUE TITLE
Explain in README.md what is the "Protected" mode for a page

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Content#6]

**Comment by warpech** [comment]
@diliger please take this as well. Try to figure out the meaning of the "Protected" checkbox from the code. If it is not obvious, please consult @miyconst.

**Comment by diliger** [comment]
`Protected` page renders only for authenticated users.

**Comment by warpech** [comment]
Please add it to README.md, in a similar manner how I explained Website features in: https://github.com/StarcounterPrefabs/Website/blob/develop/README.md#features

**Comment by diliger** [comment]
PR #15

**Comment by diliger** [comment]
Merged. Closed.
