### ISSUE TITLE
Need to press "Save" button twice to properly save

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Content#7]
Sometimes, when I press the "Save" button, the HTML editor changes are sent in the same WebSocket frame after the "SaveClick$" event.

In result, `.json.cs` handler for `SaveClick$` executes before the new value for `Html$` is applied.

``` json
[
{"op":"replace","path":"/_ver#c$","value":1},
{"op":"test","path":"/_ver#s","value":0},
{"op":"replace","path":"/CurrentPage/Content/SaveClick$","value":"1"},
{"op":"replace","path":"/CurrentPage/Content/Item/Html$","value":"Test Marcins"}
]
```

@chrhol any ideas how to fix this?

**Comment by miyconst** [comment]
I am not sure this could be managed on server side. We should send save click event with a timeout as a separate patch.

**Comment by warpech** [comment]
Fixed in PR #10

**Comment by diliger** [comment]
Tested.
Can be closed.

**Comment by warpech** [comment]
Thanks, closing
