### ISSUE TITLE
Apply BEM to Content's private CSS

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Content#8]
This app contains globally applied CSS rules in stylesheets: https://github.com/StarcounterSamples/Content/blob/e3e8a5396f875f4f824924d3ffe47d9c98d2213e/src/Content/wwwroot/Content/css/standalone.css

It also contains inline CSS in HTML templates: 
https://github.com/StarcounterSamples/Content/search?utf8=%E2%9C%93&q=filename%3A.html+style&type=Code

All private CSS should be converted to BEM-style CSS classes defined in a stylesheet, according to the intent started in the issue https://github.com/Starcounter/Starcounter/issues/3450 and explained in the article http://starcounter.io/guides/web/avoiding-css-conflicts/

**Comment by diliger** [comment]
I think I shouldn't modify files inside `/sys/` folder, should I?

**Comment by warpech** [comment]
Of course not, BEM-ification only applies to Content app styles that are in wwwroot/content

**Comment by diliger** [comment]
how to apply BEM if style is for elements that aren't presented on the page
for example this
![image](https://cloud.githubusercontent.com/assets/15857369/22595656/780a8640-ea39-11e6-8486-06346d3c818d.png)

**Comment by warpech** [comment]
The above usage is against good practices and should be removed. If it looks wrong, then the only way to do it correctly is to include it in `AppHubTemplate.html`.

**Comment by diliger** [comment]
Project has such `private styles` defined:
1) https://github.com/StarcounterPrefabs/Content/blob/master/src/Content/wwwroot/Content/dynamic/index/HeaderPage.html#L5
```
html section.navigation {
    margin: 0px -50px;
    padding: 10px 50px;
}
```
but there is no such element on this page.
can i just remove the style?

**Comment by diliger** [comment]
2) https://github.com/StarcounterPrefabs/Content/blob/master/src/Content/wwwroot/Content/dynamic/apps/HeaderPage.html#L4
```
.table {
...
.table thead tr th {
...
```
what the table is about? 
how to figure out a logical name for it?

**Comment by diliger** [comment]
3) https://github.com/StarcounterPrefabs/Content/blob/master/src/Content/wwwroot/Content/dynamic/index/RegistrationPage.html#L4
```
html section.header {
    padding: 30px 5000px;
...
```
again styles for the element that's not presented on the page.
remove?

**Comment by warpech** [comment]
> can i just remove the style?

Yes, because this style violates rule 7 from https://docs.starcounter.io/guides/mapping-and-blending/avoiding-css-conflicts/

This style is a hack to a problem that no longer exists.

**Comment by warpech** [comment]
> what the table is about?
how to figure out a logical name for it?

I think it is about the table that renders when you click on the "Wanted apps" link. There should be a content HTML for that.

**Comment by warpech** [comment]
> 3 (...) again styles for the element that's not presented on the page.
remove?

Yes

**Comment by diliger** [comment]
4) https://github.com/StarcounterPrefabs/Content/blob/master/src/Content/wwwroot/Content/dynamic/NavigationPage.html#L39

styles for **div.post-content**
```
div.post-content #body {
    background-color: white;
    padding: 10px 0px;
```
but there is no static html content on the page, only some javascript code that maybe generates html on the fly.
how to fix styles?

**Comment by diliger** [comment]
5) https://github.com/StarcounterPrefabs/Content/blob/master/src/Content/wwwroot/Content/dynamic/userprofile/HeaderPage.html#L3

```
html /deep/ h3 span::before {
      display: block;
...
```
similar to previous.
no static html only javascript...

**Comment by warpech** [comment]
> 4. (...) styles for div.post-content

Remove this. Many styles in this CSS were added to style the WordPress theme from the inside. This is wrong and should be removed.

**Comment by warpech** [comment]
> 5. similar to previous.
no static html only javascript...

Remove this as well. Related to WordPress stuff.

**Comment by diliger** [comment]
Closing as done.
